language: go
go_import_path: github.com/centrifuge/precise-proofs
go:
 - 1.10.x
 - tip

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./proofs

after_success:
   bash <(curl -s https://codecov.io/bash)
